services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: kahoot
    volumes:
      - .:/kahoot-go
    working_dir: /kahoot
    ports:
      - "8080:8080"
    depends_on:
      - redis
    command: air -c .air.toml
    environment:
      - REDIS_ADDR=redis:6969

  redis:
    build: 
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    ports:
      - "6969:6969"
