services:
  kahoot:
    build: 
      context: .
      dockerfile: Dockerfile.app
    container_name: kahoot
    volumes:
      - .:/kahoot
    working_dir: /kahoot
    ports:
      - "8080:8080"
    depends_on:
      - redis
      # - tailwind
    command: air -c .air.toml
    environment:
      - REDIS_ADDR=redis:6969
    networks:
      - backend

  redis:
    build: 
      context: .
      dockerfile: Dockerfile.redis
    container_name: redis
    expose:
      - "6969"
    networks:
      - backend

networks:
  backend:
    driver: bridge
